"""new fields in user model

Revision ID: 09250e0a8012
Revises: afd31d6549f6
Create Date: 2018-02-05 20:49:32.697824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09250e0a8012'
down_revision = 'afd31d6549f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
